### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ufinal** [DawfukFR/kernel_oneplus_sm8250#1]
Do you have oneplus8t kernel for android 13 with nethunter support?

**Comment by DawfukFR** [comment]
for instant there not any kernel with nethunter support but i can try to add it

**Comment by ufinal** [comment]
perfect..i can test when its ready

**Comment by DawfukFR** [comment]
you have a telegram acc?

**Comment by ufinal** [comment]
yeah  https://t.me/ufinal
